// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralStation.Data.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220228183936_TheFirst")]
    partial class TheFirst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("CentralStation.Data.Models.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("CentralStation.Data.Models.PeerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMessageTimeSent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("LastMessageTimeSent");

                    b.HasIndex("PeerId");

                    b.ToTable("PeerConnections");
                });

            modelBuilder.Entity("CentralStation.Data.Models.PeerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeerId");

                    b.HasIndex("RequestTime");

                    b.HasIndex("ResponseTime");

                    b.ToTable("PeerMessages");
                });

            modelBuilder.Entity("CentralStation.Data.Models.PeerConnection", b =>
                {
                    b.HasOne("CentralStation.Data.Models.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });

            modelBuilder.Entity("CentralStation.Data.Models.PeerMessage", b =>
                {
                    b.HasOne("CentralStation.Data.Models.Peer", "Peer")
                        .WithMany()
                        .HasForeignKey("PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });
#pragma warning restore 612, 618
        }
    }
}
